### ISSUE TITLE
[Question] Worldedit?

### ISSUE THREAD

**Issue by TheBjoel2** [gnembon/carpetmod112#130]
What is a /carpet worldedit and how to use it?

**Comment by altrisi** [comment]
See #41.

**Comment by TheBjoel2** [comment]
Ok this was pretty stupid question, but anyway thanks for help

**Comment by Elon61** [comment]
I kind of struggled getting WorldEdit to work. the PR mostly has all the info needed, but download link is now broken and i feel that surely i couldn't have been the only one to have some trouble with the process. 

Since this is a pre-existing issue on the topic i think this is an okay place to share what ended up working for me. 

Finding the exact dependencies required was a bit of a chore since i wasn't really sure where to look. ultimately i settled on the versions listed in the [build.gradle](https://github.com/EngineHub/WorldEdit/blob/6.1/build.gradle) file of the worldedit repo, sourced from what appears to be the new maven at [enginehub.org](https://maven.enginehub.org/).

This gives us the following: 
 - [World-Edit Core 6.1](https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-core/6.1/worldedit-core-6.1.jar)
 - [jchronic-0.2.4a](https://maven.enginehub.org/artifactory/repo/com/sk89q/jchronic/0.2.4a/jchronic-0.2.4a.jar)
 - [paranamer-2.6](https://maven.enginehub.org/artifactory/repo/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar)
 - [jlibnoise-1.0.0](https://maven.enginehub.org/artifactory/repo/com/sk89q/lib/jlibnoise/1.0.0/jlibnoise-1.0.0.jar)

I put everything under ./libs and ran the server using `java -cp 'carpet.jar;libs/*' net.minecraft.server.MinecraftServer -Xmx6144M nogui`

Enable the `/carpet worldEdit` rule, and regular worldedit commands "`//`" should now work! 

I tried to get the newer snapshot version (6.1.4) working, it would load but commands would fail. adding the seemingly missing [library](https://repo1.maven.org/maven2/com/google/guava/guava/17.0/) didn't fix it so i gave up. 

Hopefully someone else will find this helpful.
