### ISSUE TITLE
JNI error when running the server.jar

### ISSUE THREAD

**Issue by ezegonmac** [gnembon/carpetmod112#145]
I followed all the steps for patching the java server file. Althought, when i tried to execute it with java( I have the last version of Java 8) I run into this error. I dont know if it is due to mi own PC or its from the code. I attach a screenshot from the cmd console.

![Captura](https://user-images.githubusercontent.com/53529939/106301885-8c92b100-6258-11eb-9e85-a73a88a6e301.PNG)

**Comment by Earthcomputer** [comment]
You probably didn't patch the jar properly, noone else has this issue.

**Comment by Elon61** [comment]
I was running into the exact same issue, using the exact same patching procedure that previously worked for me. i also tried all the other methods i could find, including gnembon's original 1.11 and the every manual method listed in the [doc](https://carpet112.readthedocs.io/en/staging/usage/install.html)... until i used the automatic script (windows pleb here so it wasn't my first choice) which made me realize the carpet mod was updated to 1.12.2. 

Manually patching the 1.12.2 server version worked perfectly fine. i thought i would share since at least one other person had the same issue i did. 
the 1.12.2 update was version v19_08_30 of the carpet mod apparently.
